# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b62561dfb965693212cf2f24bbbd11ff09557afeaaa0af64e4d580a1b1f0f5bdaf79b2661b09bf47712a8f467aa95c0ee687039a16b75ea24b59768697cfa6ca

test:
  secret_key_base: 0ac194c0585983b79b9b272b596de741e6f8617f08b5298c1eb9f4f27a831cabc93daa434c272a485b3cc31b0cfdb9a644f2fc4ea15044fdd16c079cda6a7dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
